jvsocial/learnforkandpull

sampletest.txt

testpurpose

---

sample.txt

could you please approve and merge...

A meaningful commit message

---

fileafterfolk.txt
sample.txt

Tafter pushing we are doing the pull request from github

testpullrequest

---

sample1.txt

Can you please merge chanages Javeed? I have pushed the request.

A meaningful message

---

subhankar3demo.txt
subhankarrepo2demo.txt
subhankarsample.txt

subhankar to create a pull request

doing a pull request

---

magesh.txt

Magesh.test

---

sample1.txt

Modified sample1.txt

---

new.txt

This commit is done for a new file

---

shaila.txt

my first change

---

index.html

testing pull request lab assignment

added in test branch

---

sample.txt

forkandpullsample

---

harshainagadapa.txt

i have created new file name as harshainagadapa.txt for practicing pull and push

harsha git practice

---

Testsamplefile
sample.txt

learn pull

---

1!
samplemanoj.txt

Merge Request for Samplemanoj text file

Merge Request for Samplemanoj text file

---

new.txt

initial commit

---

Teja_testing.xml

Please accept this pull request 
just commit these changes

Hi Javeed, Please accept this pull request 

---

Satish

Please add this file to your repo

Added new code inside Satish file

---

sampletest.txt

sample file

---

pull-test

Create pull-test 

---

PR.txt
pr.txt

adding PR.txt

---

mysample.txt

Hi Javed,
please accept my pull request

Abhipsha sample file

---

file0402

I added a file to your repo

---

vinayak.txt

sample vin file

---

sample.txt

I have made a changes in the file. Please review the file and approve.

Added Sample.txt file

---

sample.txt

Added sample file

---

egbyron1.txt

this is my sample file to commit

---

aryan.txt

New commit

---

ahernanr.txt

I want to upload a new file with my name.

Antonio - New File

---

Ahamed.txt

hi javeed i have added Ahamed.txt

A meaningfulcommit message

---

sample_vaibhav.txt

adding new file

---

samplebikash.txt

Bikash is only now learning fork and pull

Learning fork and pull

---

sample.txt
samplefile.txt

changes have been made, for the pull request

doing the pull request

---

pr.txt

From Naren

---

Abhijeet Fork

Hi, I just created pull request

Create Abhijeet Fork
